package io.blueeye.core.domain.scanner

enum class ScannerLifecycleTransition {
    SERVICE_CREATED,
    START_REQUESTED,
    START_IGNORED_ALREADY_ACTIVE,
    RUNNING,
    FOCUSED_SCAN_REQUESTED,
    PASSIVE_SCAN_RESUMED,
    STOP_REQUESTED,
    STOP_IGNORED_ALREADY_IDLE,
    BLUETOOTH_OFF,
    START_FAILED,
    SCANNER_FAILED,
    DESTROYED,
}

data class ScannerIngestDiagnostics(
    val windowStartedAt: Long = 0L,
    val rawBleCallbacksTotal: Long = 0L,
    val rawBleCallbacksPerMinute: Int = 0,
    val enqueueAcceptedTotal: Long = 0L,
    val enqueueAcceptedPerMinute: Int = 0,
    val enqueueRejectedTotal: Long = 0L,
    val queueDroppedTotal: Long = 0L,
    val coalescedTotal: Long = 0L,
    val coalescedPerMinute: Int = 0,
    val processingStartedTotal: Long = 0L,
    val processingSucceededTotal: Long = 0L,
    val processedPerMinute: Int = 0,
    val processingFailedTotal: Long = 0L,
    val provisionalDiscardedTotal: Long = 0L,
    val persistedDeviceUpdatesTotal: Long = 0L,
    val persistedDeviceUpdatesPerMinute: Int = 0,
    val deviceUpdateThrottledTotal: Long = 0L,
    val signalSamplesWrittenTotal: Long = 0L,
    val signalSamplesWrittenPerMinute: Int = 0,
    val signalSamplesThrottledTotal: Long = 0L,
    val signalSampleWriteFailuresTotal: Long = 0L,
    val queueDepth: Int = 0,
    val queueHighWaterMark: Int = 0,
    val lastQueueWaitMs: Long? = null,
    val totalQueueWaitMs: Long = 0L,
    val maxQueueWaitMs: Long = 0L,
    val lastProcessingDurationMs: Long? = null,
    val totalProcessingDurationMs: Long = 0L,
    val maxProcessingDurationMs: Long = 0L,
)

data class ScannerRuntimeDiagnostics(
    val runtimeProfile: ScannerRuntimeProfile = ScannerRuntimePolicy.profile,
    val state: ScannerRuntimeState = ScannerRuntimeState.Idle,
    val startedAt: Long? = null,
    val lastBleResultAt: Long? = null,
    val lastBleMac: String? = null,
    val lastClassicResultAt: Long? = null,
    val lastClassicMac: String? = null,
    val bleResultsPerMinute: Int = 0,
    val classicResultsPerMinute: Int = 0,
    val droppedQueueEvents: Long = 0L,
    val ingest: ScannerIngestDiagnostics = ScannerIngestDiagnostics(),
    val lastScanError: String? = null,
    val lastLifecycleTransition: ScannerLifecycleTransition? = null,
    val lastLifecycleTransitionAt: Long? = null,
    val lifecycleTransitionCount: Long = 0L,
    val updatedAt: Long = 0L,
)
