from pathlib import Path

screen = Path('feature/details/src/main/java/io/blueeye/feature/details/DetailsScreen.kt')
text = screen.read_text()
old = '''                // Technical and diagnostic actions stay available, but below decision content.\n                ConnectionCard(\n                    connectionState = connectionState,\n                    onConnect = { viewModel.connect() },\n                    onDisconnect = { viewModel.disconnect() }\n                )\n\n                if (sensorData != null) {\n                    SensorDataCard(sensorData!!)\n                }\n\n                InfoSection("Activity",\n                    listOf(\n                        "First Seen" to DetailsUiFormatter.formatFriendlyTimestamp(dev.firstSeenAt),\n                        "Last Seen" to DetailsUiFormatter.formatFriendlyTimestamp(dev.lastSeenAt),\n                        "Encounters" to dev.encounterCount.toString()\n                    )\n                )\n\n                InfoSection("Radio",\n                    listOf(\n                        "PHY" to DetailsUiFormatter.formatPhy(dev.primaryPhy, dev.secondaryPhy),\n                        "Interval" to (dev.advertisingIntervalMs?.let { "~${it}ms" } ?: "Unknown"),\n                        "Beacon Type" to (dev.beaconType ?: "N/A")\n                    )\n                )\n\n                // Extended Info (Conditional)\n                val extendedProps =\n                    listOfNotNull(\n                        dev.modelNumber?.let { "Model" to it },\n                        dev.serialNumber?.let { "Serial" to it },\n                        dev.firmwareRevision?.let { "Firmware" to it },\n                        dev.batteryLevel?.let { "Battery" to "$it%" }\n                    )\n                if (extendedProps.isNotEmpty()) {\n                    InfoSection("Extended Info", extendedProps)\n                }\n\n                // Services\n                if (services.isNotEmpty()) {\n                    InfoSection("Services (${services.size})", services.map { it.uuid to it.name })\n                }\n'''
new = '''                InfoSection(\n                    title = "History",\n                    items =\n                        listOf(\n                            "First Seen" to DetailsUiFormatter.formatFriendlyTimestamp(dev.firstSeenAt),\n                            "Last Seen" to DetailsUiFormatter.formatFriendlyTimestamp(dev.lastSeenAt),\n                            "Encounters" to dev.encounterCount.toString(),\n                        ),\n                )\n\n                DetailsTechnicalSection(\n                    state =\n                        DetailsTechnicalState(\n                            device = dev,\n                            connectionState = connectionState,\n                            sensorData = sensorData,\n                            services = services,\n                        ),\n                    onConnect = { viewModel.connect() },\n                    onDisconnect = { viewModel.disconnect() },\n                )\n'''
assert text.count(old) == 1
screen.write_text(text.replace(old, new, 1))

technical = Path('feature/details/src/main/java/io/blueeye/feature/details/DetailsTechnicalSection.kt')
assert not technical.exists()
technical.write_text('''package io.blueeye.feature.details\n\nimport androidx.compose.foundation.layout.Arrangement\nimport androidx.compose.foundation.layout.Column\nimport androidx.compose.foundation.layout.fillMaxWidth\nimport androidx.compose.material3.MaterialTheme\nimport androidx.compose.material3.Text\nimport androidx.compose.runtime.Composable\nimport androidx.compose.ui.Modifier\nimport io.blueeye.core.model.Device\nimport io.blueeye.core.model.DeviceConnectionState\nimport io.blueeye.core.model.GattService\nimport io.blueeye.core.model.SensorData\nimport io.blueeye.core.ui.theme.Dimens\n\ninternal data class DetailsTechnicalState(\n    val device: Device,\n    val connectionState: DeviceConnectionState,\n    val sensorData: SensorData?,\n    val services: List<GattService>,\n)\n\n@Composable\ninternal fun DetailsTechnicalSection(\n    state: DetailsTechnicalState,\n    onConnect: () -> Unit,\n    onDisconnect: () -> Unit,\n    modifier: Modifier = Modifier,\n) {\n    val device = state.device\n    Column(\n        modifier = modifier.fillMaxWidth(),\n        verticalArrangement = Arrangement.spacedBy(Dimens.PaddingMedium),\n    ) {\n        Text(\n            text = "Technical details",\n            style = MaterialTheme.typography.titleMedium,\n            color = MaterialTheme.colorScheme.primary,\n        )\n\n        ConnectionCard(\n            connectionState = state.connectionState,\n            onConnect = onConnect,\n            onDisconnect = onDisconnect,\n        )\n\n        state.sensorData?.let { data ->\n            SensorDataCard(data)\n        }\n\n        InfoSection(\n            title = "Radio",\n            items =\n                listOf(\n                    "PHY" to DetailsUiFormatter.formatPhy(device.primaryPhy, device.secondaryPhy),\n                    "Interval" to (device.advertisingIntervalMs?.let { "~${it}ms" } ?: "Unknown"),\n                    "Beacon Type" to (device.beaconType ?: "N/A"),\n                ),\n        )\n\n        val metadata =\n            listOfNotNull(\n                device.serialNumber?.let { "Serial" to it },\n                device.firmwareRevision?.let { "Firmware" to it },\n                device.batteryLevel?.let { "Battery" to "$it%" },\n            )\n        if (metadata.isNotEmpty()) {\n            InfoSection(\n                title = "Device metadata",\n                items = metadata,\n            )\n        }\n\n        if (state.services.isNotEmpty()) {\n            InfoSection(\n                title = "Services (${state.services.size})",\n                items = state.services.map { service -> service.uuid to service.name },\n            )\n        }\n    }\n}\n''')
